# Generated by Django 4.0.2 on 2022-02-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(default=None, upload_to='<django.db.models.fields.AutoField>'),
        ),
    ]
