# Generated by Django 4.0.2 on 2022-02-06 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_face_identification_moment_remove_image_people_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moment',
            name='tagged',
        ),
    ]
