# Generated by Django 4.0.2 on 2022-02-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_person_encoding_user_alter_profile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(default=None, upload_to='uploads/pictures/'),
        ),
    ]
