# Generated by Django 4.0.2 on 2022-02-06 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_moment_tagged'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default=None, upload_to='')),
                ('moment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.moment')),
            ],
        ),
    ]
