# Generated by Django 4.0.2 on 2022-02-05 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_image_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img',
            new_name='image_file',
        ),
    ]
